// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WebApplication1Context))]
    [Migration("20240814190400_bdCursos")]
    partial class bdCursos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.curso", b =>
                {
                    b.Property<int>("cursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cursoId"), 1L, 1);

                    b.Property<int>("departamentodepid")
                        .HasColumnType("int");

                    b.Property<int>("depid")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cursoId");

                    b.HasIndex("departamentodepid");

                    b.ToTable("curso");
                });

            modelBuilder.Entity("WebApplication1.Models.cursoDisciplina", b =>
                {
                    b.Property<int>("cursoDisciplinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cursoDisciplinaID"), 1L, 1);

                    b.Property<int>("cursoID")
                        .HasColumnType("int");

                    b.Property<int>("disciplinaID")
                        .HasColumnType("int");

                    b.HasKey("cursoDisciplinaID");

                    b.HasIndex("cursoID");

                    b.HasIndex("disciplinaID");

                    b.ToTable("cursoDisciplina");
                });

            modelBuilder.Entity("WebApplication1.Models.departamento", b =>
                {
                    b.Property<int>("depid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("depid"), 1L, 1);

                    b.Property<string>("depnome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("instid")
                        .HasColumnType("int");

                    b.Property<int>("instituicaoinstid")
                        .HasColumnType("int");

                    b.HasKey("depid");

                    b.HasIndex("instituicaoinstid");

                    b.ToTable("departamento");
                });

            modelBuilder.Entity("WebApplication1.Models.disciplina", b =>
                {
                    b.Property<int>("disciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("disciplinaId"), 1L, 1);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("disciplinaId");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("WebApplication1.Models.instituicao", b =>
                {
                    b.Property<int>("instid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("instid"), 1L, 1);

                    b.Property<string>("insendereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instnome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("instid");

                    b.ToTable("instituicao");
                });

            modelBuilder.Entity("WebApplication1.Models.curso", b =>
                {
                    b.HasOne("WebApplication1.Models.departamento", "departamento")
                        .WithMany("curso")
                        .HasForeignKey("departamentodepid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departamento");
                });

            modelBuilder.Entity("WebApplication1.Models.cursoDisciplina", b =>
                {
                    b.HasOne("WebApplication1.Models.curso", "curso")
                        .WithMany("cursoDisciplina")
                        .HasForeignKey("cursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.disciplina", "disciplina")
                        .WithMany("cursoDisciplina")
                        .HasForeignKey("disciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("curso");

                    b.Navigation("disciplina");
                });

            modelBuilder.Entity("WebApplication1.Models.departamento", b =>
                {
                    b.HasOne("WebApplication1.Models.instituicao", "instituicao")
                        .WithMany("departamento")
                        .HasForeignKey("instituicaoinstid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("instituicao");
                });

            modelBuilder.Entity("WebApplication1.Models.curso", b =>
                {
                    b.Navigation("cursoDisciplina");
                });

            modelBuilder.Entity("WebApplication1.Models.departamento", b =>
                {
                    b.Navigation("curso");
                });

            modelBuilder.Entity("WebApplication1.Models.disciplina", b =>
                {
                    b.Navigation("cursoDisciplina");
                });

            modelBuilder.Entity("WebApplication1.Models.instituicao", b =>
                {
                    b.Navigation("departamento");
                });
#pragma warning restore 612, 618
        }
    }
}
